apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: test-namespace
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; 
            - pwd;
          restartPolicy: OnFailure
