apiVersion: v1
kind: Service
metadata:
  name: docker-authentication-service
spec:
  selector:
    app: docker-authentication-service
  ports:
    - port: 35350
      targetPort: 2300
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-authentication-service
  template:
    metadata:
      labels:
        app: docker-authentication-service
    spec:
      containers:
        - name: docker-authentication-service
          image: bhaarn/docker_authentication_service:latest
          ports:
            - containerPort: 2300
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: docker-authentication-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docker-authentication-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
